version: '3'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data:/data/db
    ports:
      - ${DB_PORT}:${DB_PORT}
  backend:
    build:
      context: ./back-end
    restart: always
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST_CONTAINER}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      BACKEND_PORT: ${BACKEND_PORT}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - mongo
